In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [9]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [10]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [12]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [22]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)
print(arr1)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]]


In [36]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2)) #h stands for horizontal

print(arr)

[1 2 3 4 5 6]


In [34]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2)) #v stands for vertical

print(arr)

[[1 2 3]
 [4 5 6]]


In [40]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [55]:
arr = np.array([1, 2, 3, 4, 5, 6, 8])

newarr = np.array_split(arr, 9)

print(newarr)  ### most important when out of index, like 6 elements and 9 is the split criteria

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([8]), array([], dtype=int32), array([], dtype=int32)]


In [50]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [54]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 1)

print(newarr)

[array([1, 2, 3, 4, 5, 6])]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.arry_split(arr, 4)

print(newarr)

AttributeError: module 'numpy' has no attribute '_split'

In [57]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]
