In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
type(arr)

numpy.ndarray

In [4]:
np.version

<module 'numpy.version' from 'C:\\Users\\ADMIN\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [7]:
d = np.full((3, 3), 2, dtype = 'float')

In [13]:
d = np.full((3, 3), 2, dtype = 'int')
print ("\nAn array initialized with all 2s."
            "Array type is complex:\n", d)


An array initialized with all 2s.Array type is complex:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [14]:
print(arr.ndim)

3


In [15]:
arr = np.array([[[[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]]],[[[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]]],[[[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]]]])

print(arr)

[[[[1 2 3 4 5]
   [1 2 3 4 5]]]


 [[[1 2 3 4 5]
   [1 2 3 4 5]]]


 [[[1 2 3 4 5]
   [1 2 3 4 5]]]]


In [16]:
print(arr.ndim)

4


In [17]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [18]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 0, 2])

3


In [21]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [25]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [30]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [31]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [39]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [40]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
