In [27]:
import numpy as np
from numpy import random

In [3]:

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)   #prints the index where 4 is present

(array([3, 5, 6], dtype=int64),)


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%3== 0)

print(x)

(array([2, 5], dtype=int64),)


In [12]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 9)

print(x)

3


In [14]:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)   #indexing start from right side

2


In [15]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)   #printing the given values's indexes taking account that they are present 

[1 2 3]


In [17]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [18]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [19]:

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [20]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [25]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [26]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [29]:
x = random.rand()

print(x)

0.9961032627986486


In [30]:

x=random.randint(100, size=(5))

print(x)

[26 14 76 70 15]


In [31]:
x = random.randint(100, size=(3, 5))

print(x)

[[34 52 85 90 49]
 [91 19 32 25 90]
 [ 2 47 46 24 86]]


In [33]:
x = random.rand(5)

print(x) #creating randomvalue in between 0 and 1

[0.52407233 0.44429536 0.24298249 0.10728614 0.42286506]
